apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app-img
  name: app-img
  namespace: mynamespace
spec:
  containers:
  - image: web-template-app:1
    name: app-img
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
