apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy-box
  name: busy-box
  namespace: mynamespace
spec:
  containers:
  - command:
    - env
    image: busybox
    name: busy-box
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
